### PR TITLE
Add systemd service

### PR DESCRIPTION
**Pull request by rumpelsepp**
Not sure if this actually works. Please leave this open until I can do more testing and actually setup my own discovery server.

### CODE REVIEW

**Comment by calmh** [comment]
Should be fine; the discosrv runs with default config if given no arguments, never exits and never restarts. So you can probably skip the successexit stuff as well.

**Comment by rumpelsepp** [comment]
Yeah. I have to investigate if the security options make sense and work as well. For the time being I just copied some boilerplate and tweaked it a bit. I will setup that stuff and finish the service files soon. :-)

**Comment by calmh** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/syncthing/discosrv/19)

**Comment by rumpelsepp** [comment]
Ah, I forgot about this. This needs fixing.

**Comment by calmh** [comment]
Yeah this one needs certificates and crap now. Unsure how best to handle that from systemd.


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/syncthing/discosrv/19)

**Comment by rumpelsepp** [comment]
> Yeah this one needs certificates and crap now. Unsure how best to handle that from systemd.

Just the same how we do it in relaysrv; I just forgot about this one here...

**Comment by calmh** [comment]
Yeah sorry about that.

**Comment by rumpelsepp** [comment]
No worries, sry about me being (possibly?) rude. :dancers:

**Comment by calmh** [comment]
No I fully agree with you. It's a review tool, nice, but it should cut that crap out.

**Comment by st-review** [comment]
I'm going to close this pull request as it has been idle for more than 90 days.

This is not a permanent rejection, merely a removal from the list of active pull requests that is periodically reviewed by humans. The pull request can be reopened when there is new activity, and merged once any remaining issues are resolved.

**Pull request closed without merging**
