### PR TITLE
Accept any URI for announce addresses

### LINKED ISSUE #46: Accept domain names in announced addresses
I've been trying to configure syncthing to use FQDN for a private relay server, but it didn't work unless I used relay server's public IP address. Apparently, the current implementation [only accepts IP addresses](https://github.com/syncthing/discosrv/blob/master/querysrv.go#L332) in the announce POST request. If domain names were sent by the client, they will be replaced by client's IP address.

### PR DESCRIPTION
**Pull request by majedev**
Resolves #46. Just removed IP address checks. Tested with private relay using domain name and relaying works as expected.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
So I don't think this is the right fix.
I think the right fix is this:

```
		ip := net.ParseIP(host)
		if host == "" && (len(ip) == 0 || ip.IsUnspecified()) {
			host = remote.String() 
		}
		uri.Host = net.JoinHostPort(host, port)
```

So that when the client advertises `tcp://:22000` we still expand the address to `tcp://<clients remote address>:22000`

**Comment by majedev** [comment]
Woops, you're right. My bad!

**Comment by majedev** [comment]
Just seen your edit. I think `ip.IsUnspecified()` check should be kept for `tcp://0.0.0.0:22000` addresses.

**Comment by AudriusButkevicius** [comment]
Ah yes, you are right.

**Pull request closed without merging**
