### PR TITLE
Defer fd.Close() (fixes #37)

### LINKED ISSUE #37: Defer fd.Close() in stats.go?
I was just browsing the source code and saw this: https://github.com/syncthing/discosrv/blob/master/stats.go#L131

Wouldn't it be better to do something like this right after `fd.OpenFile` succeeds?
```
	defer func() {
		err = fd.Close()
		if err != nil {
			log.Println("stats file:", err)
		}
	}
```

### PR DESCRIPTION
**Pull request by kc1212**
Should be self explanatory, fixes #37

### CODE REVIEW

**Comment by calmh** [comment]
What happens if we're already returning another error though - say, if the write fails. There's a risk we overwrite it with a nil error from the close?

**Comment by calmh** [comment]
@st-jenkins add to whitelist

**Comment by calmh** [comment]
@st-jenkins add to whitelist

**Comment by kc1212** [comment]
The function isn't propagating the error back to the caller, it only prints the error, so overwriting shouldn't cause a problem. With that said, there would be a problem if the function is changed later to return the error, I suppose it's better to keep the `err` variable within the deferred function's scope.

**Comment by calmh** [comment]
Indeed, I only read the diff. That function is a bit of a WTF as it *should* return an error to the caller instead, but what the hell.

**Pull request merged**
